#!/usr/bin/env python3
"""Vendor the campaign science kernel from tamarind-agent into both plugins.

The miniprotein campaign skill needs the frozen score algebra, the liability and
plausibility gates, the target-mimic screen and the selection caps to run the
SAME way every time. Re-deriving those formulas from prose is the defect this
vendoring exists to prevent: the plausible wrong version of each one is silently
wrong in the permissive direction (drop the +1 in novelty coverage and every hit
under-reports, which errs toward ADMITTING a design at the reject threshold).

Source of truth is tamarind-agent. This script copies the modules verbatim,
rewrites their intra-package imports to relative ones, and writes a manifest
naming the source commit so drift is detectable rather than silent.

Usage:
  python3 tools/vendor_campaign_kernel.py --agent-repo /path/to/tamarind-agent
  python3 tools/vendor_campaign_kernel.py --agent-repo ... --ref pr-367 --check
"""
import argparse
import ast
import hashlib
import pathlib
import re
import subprocess
import sys

SRC_PREFIX = "campaign/cda/subagents"

# Transitive closure of what the campaign skill calls, verified by tracing the
# import graph: every module below is stdlib + numpy plus other members of this
# list. Nothing here reaches the campaign app, the database or the network.
MODULES = [
    "qa_analysis_helpers",     # score algebra, liability gates, cif->pdb, DSSP fold class
    "qa_tm_helpers",           # TM-score and the target-mimic gate
    "prescoring_rejects",      # verdict tokens and the gate registry
    "structure_plausibility",  # backbone geometry, clashes, core packing
    "qa_selection_helpers",    # TM clustering and the diversity-cap selector
    "local_alignment",         # gapped local identity
    "novelty_gate",            # the novelty verdict over its subject sets
    "screen_gate_metrics",     # monomer foldability and the ESM-C log-likelihood
    "sheet_recompute",         # the write-time recompute that halts on a mismatch
]

# The only things the kernel needs from `campaign.cda.prompts.qa_rubrics`, which
# is a 3,900-line prompt module we do not want. Read out of that module AT THE
# VENDORED REF rather than hardcoded: a hardcoded copy writes the old values
# while the manifest records the new commit, so `--check` would report the tree
# current with thresholds that no longer match the revision it names -- which is
# the exact drift this tool exists to detect.
RUBRIC_NAMES = (
    "ESMC_LL_TOOL",
    "MONOMER_CHECK_NOT_RUN_CODE",
    "MONOMER_GATE_STAGE_TOKEN",
    "MONOMER_PLDDT_FLOOR_THRESHOLD",
    "MONOMER_PLDDT_SEED_AGGREGATION",
    "MONOMER_ROW_MEASUREMENT_TERM",
)
RUBRICS_PATH = "campaign/cda/prompts/qa_rubrics.py"


def extract_rubric_constants(source: str) -> str:
    """Lift the named module-level constants out of qa_rubrics at the vendored ref.

    Matches a top-level `NAME = <literal>` on one line. Every constant needed is
    a bare string or float today; anything else raises rather than being
    silently skipped, because a missing constant becomes an ImportError in the
    vendored tree and a WRONG one becomes a threshold nobody notices.
    """
    found: dict[str, str] = {}
    for name in RUBRIC_NAMES:
        match = re.search(rf"^{re.escape(name)} = (.+)$", source, re.MULTILINE)
        if not match:
            raise SystemExit(
                f"{name} not found as a top-level constant in {RUBRICS_PATH}. "
                "Upstream moved or renamed it; update RUBRIC_NAMES rather than "
                "vendoring a tree that cannot import."
            )
        value = match.group(1).strip()
        try:
            ast.literal_eval(value)
        except (ValueError, SyntaxError) as exc:
            raise SystemExit(f"{name} is not a literal ({value!r}): {exc}")
        found[name] = value
    body = "".join(f"{name} = {found[name]}\n" for name in RUBRIC_NAMES)
    return (
        '"""Constants the kernel needs from the campaign\'s QA rubrics.\n\n'
        "Generated by tools/vendor_campaign_kernel.py, read out of\n"
        f"{RUBRICS_PATH} at the vendored commit rather than hardcoded here.\n"
        "Do not edit by hand -- re-vendor instead.\n"
        '"""\n\n' + body
    )


INIT = '''"""Vendored campaign science kernel -- do not edit by hand.

Regenerate with `python3 tools/vendor_campaign_kernel.py --agent-repo ...`.
See VENDORED.md for the source commit.
"""
'''

DESTS = [
    "plugins/tamarind-mcp/skills/tamarind-mcp-miniprotein-campaign/scripts/_kernel",
    "plugins/tamarind-cli/skills/tamarind-miniprotein-campaign/scripts/_kernel",
]


def recorded_ref() -> str:
    """The ref the current tree was actually vendored from.

    `--ref` used to default to `main`, but `campaign/cda/` does not exist
    there -- the modules live on an unmerged branch. The default therefore
    failed for anyone who did not already know to pass `--ref`, and it failed
    as a raw CalledProcessError rather than a diagnosis, so `--check` (the
    whole point of the manifest) was inoperable out of the box.

    Read the ref back from the manifest instead of restating it here: a
    constant copied into a second place is a constant that goes stale, and
    this one is already written down by the generator below.
    """
    for dest in DESTS:
        manifest = pathlib.Path(__file__).resolve().parents[1] / dest / "VENDORED.md"
        if not manifest.exists():
            continue
        found = re.search(r"^- ref: `([^`]+)`", manifest.read_text(), re.M)
        if found:
            return found.group(1)
    return "main"


def rewrite(text: str) -> str:
    """Point intra-package imports at the vendored copy.

    Two independent substitutions on disjoint patterns. An earlier version
    routed through a placeholder and then ran a global
    `replace("from ._", "from .")`, which strips the leading underscore off ANY
    relative import -- including the `._rubric_constants` one this function
    itself introduces. Nothing upstream imports relatively today, so it never
    fired, but a rewriter that corrupts its own output the moment upstream adds
    one is a trap. Keep these as two plain, order-independent replacements.
    """
    text = text.replace(
        "from campaign.cda.prompts.qa_rubrics import", "from ._rubric_constants import"
    )
    return re.sub(r"from campaign\.cda\.subagents\.(\w+) import", r"from .\1 import", text)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--agent-repo", required=True, help="path to a tamarind-agent checkout")
    ap.add_argument(
        "--ref",
        default=recorded_ref(),
        help="git ref to vendor from (defaults to the ref recorded in VENDORED.md)",
    )
    ap.add_argument("--check", action="store_true", help="fail if the tree is stale")
    args = ap.parse_args()

    repo = pathlib.Path(args.agent_repo).expanduser().resolve()
    if not (repo / ".git").exists():
        print(f"not a git checkout: {repo}", file=sys.stderr)
        return 2

    def git(*a: str) -> str:
        done = subprocess.run(
            ["git", "-C", str(repo), *a], capture_output=True, text=True
        )
        if done.returncode:
            # A missing ref or path is the ORDINARY failure here -- the kernel
            # lives on a branch, so a checkout without it is the common case.
            # Say which ref and which path, because an unhandled
            # CalledProcessError told the operator neither.
            raise SystemExit(
                f"git {' '.join(a)} failed in {repo}:\n"
                f"  {done.stderr.strip()}\n"
                f"  The kernel is vendored from `{SRC_PREFIX}/` at ref "
                f"`{args.ref}`. Fetch that ref in the agent checkout, or pass "
                f"--ref with one that carries it."
            )
        return done.stdout

    commit = git("rev-parse", args.ref).strip()
    rubrics = git("show", f"{args.ref}:{RUBRICS_PATH}")
    files = {
        "__init__.py": INIT,
        "_rubric_constants.py": extract_rubric_constants(rubrics),
    }
    for mod in MODULES:
        files[f"{mod}.py"] = rewrite(git("show", f"{args.ref}:{SRC_PREFIX}/{mod}.py"))

    digest = hashlib.sha256(
        "".join(f"{k}\0{v}\0" for k, v in sorted(files.items())).encode()
    ).hexdigest()
    files["VENDORED.md"] = (
        "# Vendored campaign kernel\n\n"
        "Generated by `tools/vendor_campaign_kernel.py`. Do not edit these files by hand.\n\n"
        f"- source: `Tamarind-Bio/tamarind-agent` `{SRC_PREFIX}/`\n"
        f"- ref: `{args.ref}`\n"
        f"- commit: `{commit}`\n"
        f"- content digest: `{digest}`\n\n"
        "Modules:\n\n"
        + "".join(f"- `{m}.py`\n" for m in MODULES)
        + "\nRe-vendor after any upstream change to the score algebra, the gates or the\n"
        "selection caps. A stale kernel computes different numbers than the campaign\n"
        "agent does, which is exactly the divergence the frozen instrument forbids.\n"
    )

    stale = []
    for dest in DESTS:
        d = pathlib.Path(dest)
        for name, body in files.items():
            p = d / name
            if args.check:
                if not p.exists() or p.read_text() != body:
                    stale.append(str(p))
                continue
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(body)

    if args.check:
        if stale:
            print("stale vendored files:\n  " + "\n  ".join(stale), file=sys.stderr)
            return 1
        print(f"kernel is current at {commit}")
        return 0

    print(f"vendored {len(MODULES)} modules at {commit} into {len(DESTS)} plugins")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
