"""Constants the kernel needs from the campaign's QA rubrics.

Generated by tools/vendor_campaign_kernel.py, read out of
campaign/cda/prompts/qa_rubrics.py at the vendored commit rather than hardcoded here.
Do not edit by hand -- re-vendor instead.
"""

ESMC_LL_TOOL = "esmc-6b:scan"
MONOMER_CHECK_NOT_RUN_CODE = "MONOMER_FOLDABILITY_NOT_RUN"
MONOMER_GATE_STAGE_TOKEN = "s1b_monomer"
MONOMER_PLDDT_FLOOR_THRESHOLD = 0.70
MONOMER_PLDDT_SEED_AGGREGATION = "max"
MONOMER_ROW_MEASUREMENT_TERM = "monomer_plddt"
